name: chalk
description: A Flutter project for the idea Chalk.

# publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:

  contacts_service: ^0.6.3
  call_log: ^4.0.0
  permission_handler: ^10.3.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
    
  webview_flutter: ^4.2.2
  english_words: ^4.0.0
  provider: ^6.0.0
  http: ^1.1.0
  desktop_webview_window: ^0.2.0

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0



flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

